### ISSUE TITLE
Android 14 crash when pressing the Record a Walk button

### ISSUE THREAD

**Issue by francisli** [sfbrigade/intentional-walk-client#82]
Observing two different exceptions, first with push notification library:

```
04-15 17:58:53.526 17946 17985 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
04-15 17:58:53.526 17946 17985 E AndroidRuntime: Process: org.codeforsanfrancisco.intentionalwalk, PID: 17946
04-15 17:58:53.526 17946 17985 E AndroidRuntime: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process org.codeforsanfrancisco.intentionalwalk. Make sure to call FirebaseApp.initializeApp(Context) first.
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessaging.getInstance(com.google.firebase:firebase-messaging@@21.1.0:1)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at com.dieam.reactnativepushnotification.modules.RNPushNotification.requestPermissions(RNPushNotification.java:140)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
04-15 17:58:53.526 17946 17985 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

And the second with Google Fit:

```
04-15 17:58:58.363 18922 18962 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'com.reactnative.googlefit.StepCounter com.reactnative.googlefit.GoogleFitManager.getStepCounter()' on a null object reference
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at com.reactnative.googlefit.GoogleFitModule.observeSteps(GoogleFitModule.java:131)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at com.facebook.jni.NativeRunnable.run(Native Method)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
04-15 17:58:58.363 18922 18962 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by francisli** [comment]
Also...

```
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: Exception in native call
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: java.lang.SecurityException: Caller org.codeforsanfrancisco.intentionalwalk needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3182)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Parcel.createException(Parcel.java:3166)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Parcel.readException(Parcel.java:3149)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Parcel.readException(Parcel.java:3091)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:319)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.app.AlarmManager.setImpl(AlarmManager.java:1084)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.app.AlarmManager.setImpl(AlarmManager.java:1044)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.app.AlarmManager.setExact(AlarmManager.java:808)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendNotificationScheduledCore(RNPushNotificationHelper.java:180)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendNotificationScheduled(RNPushNotificationHelper.java:159)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at com.dieam.reactnativepushnotification.modules.RNPushNotification.scheduleLocalNotification(RNPushNotification.java:183)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at com.facebook.jni.NativeRunnable.run(Native Method)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:959)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Looper.loopOnce(Looper.java:232)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:317)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:1012)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: Caused by: android.os.RemoteException: Remote stack trace:
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at com.android.server.alarm.AlarmManagerService$4.set(AlarmManagerService.java:2885)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:189)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Binder.execTransactInternal(Binder.java:1501)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 	at android.os.Binder.execTransact(Binder.java:1440)
04-22 11:58:19.692 24541 24612 E unknown:ReactNative: 
```
